### ISSUE TITLE
ci: Wait for project workflow success

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/copier-uv#24]
After generating the project, we could actually push it to our dummy repo (pawamoy-testing), triggering its own CI workflow. Then we could use GitHub's API to identify this workflow run and wait for it to succeed.

- list workflow runs for a repo: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-repository
- get workflow run: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#get-a-workflow-run (use `status` or `conclusion`)

**Comment by blakeNaccarato** [comment]
Thanks for the heads-up on Mastodon. I mentioned/tracked this issue over in my Discussion post https://github.com/blakeNaccarato/copier-python/discussions/402, as I'm interested in implementing a similar flow.

TIL that Issue mentions in Discussions don't automatically back-reference to the Issue topic! That might affect my consideration of my template's Discussions-first approach, with Issues as actual actionable work items, if Discussions don't ping/link their mentions.

Anyways, I'm getting off-topic. I am a bit pre-occupied with trying to finish up thesis work, but if you're looking for a set of eyes to review a PR or work-in-progress on this, drop me a line.

**Comment by pawamoy** [comment]
> TIL that Issue mentions in Discussions don't automatically back-reference as mentions on the Issue topic!

Yep, that is very annoying.

> Anyways, I'm getting off-topic. I am a bit pre-occupied with trying to finish up thesis work, but if you're looking for a set of eyes to review a PR or work-in-progress on this, drop me a line.

I'll keep you posted! All the best for your thesis work :smile:

**Comment by blakeNaccarato** [comment]
I appreciate the peek behind the curtain! I never bother to squash, and haven't decided whether I should be doing so, so my repos end up with absolute tons of commits, even when merging relatively small PRs. So I always feel I'm doing a lot sloppier work in comparison to these neat PRs 😅
