### ISSUE TITLE
make setup in new project fails

### ISSUE THREAD

**Issue by elyase** [pawamoy/copier-uv#39]
Error message:
```
with: pdm.backend.exceptions.ConfigError: Cannot find the version from SCM or SCM isn't detected.
```

**Comment by pawamoy** [comment]
Hmm yeah the project is configured to use dynamic versioning, picking the version from Git tags. You'll need to init your project as a Git repository to get rid of this error:

```bash
cd myproject
git init .
```

**Comment by elyase** [comment]
yes this solves the issue thanks
